#!/usr/bin/env zsh

# Run make_alias AppleScript

output=$(./make_alias.applescript "$@" 2>&1)
if [[ $output =~ ".*Created alias.*" ]]; then
    echo "Created alias"
    exit 0
elif [[ $output =~ ".* parent.*does not exist.*" ]]; then
    echo "A parent folder of $2 does not exist"
    exit 4
elif [[ $output =~ ".* does not exist.*" ]]; then
    echo "$1 does not exist"
    exit 1
elif [[ $output =~ ".* alias to an alias.*" ]]; then
    echo "$1 is an alias. Cannot create aliases of aliases"
    exit 2
elif [[ $output =~ ".* there is already an item with that name.*" ]]; then
    echo "$2 already exists"
    exit 3
elif [[ $output =~ ".*Usage.*" ]]; then
    echo "Usage: alias_target <alias_file>"
    exit 5
else
    echo "Error: Unknown result: $output"
    exit 6
fi
